version: '3.7'

networks:
  default:

volumes:
  redis:

services:
  redis:
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  relay:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - target: ${PORT:-5555}
        published: ${PORT:-5555}
        mode: host
    env_file:
      - .env