version: '3.7'

networks:
  default:

volumes:
  redis:

services:
  redis:
    image: 'redis:6-alpine'
    volumes:
      - redis:/data

  relay:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - GITHASH=00001
      - HOST=${HOST:-localhost}
      - PORT=${PORT:-5555}
      - NODE_ENV=${NODE_ENV:-development}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - REDIS_PREFIX=${REDIS_PREFIX:-terra-wc-relay}
      - REDIS_MAX_TTL=${REDIS_MAX_TTL:-604800}
